services:
  server:
    build: .
    container_name: reflectly-server
    image: reflectly-server:latest
    restart: unless-stopped
    expose:
      - "8000"
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    env_file:
      - .env
    networks:
      - reflectly_network
    volumes:
      - ./logs:/app/logs

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: reflectly-tunnel
    restart: unless-stopped
    networks:
      - reflectly_network
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel run
networks:
  reflectly_network:
    driver: bridge

