services:
  server:
    build: .
    container_name: reflectly-server
    image: reflectly-server:latest
    restart: unless-stopped
    expose:
      - "8000"
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://root:secretKey@db:5432/reflectly}
    networks:
      - reflectly_network
    volumes:
      - ./logs:/app/logs

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: reflectly-tunnel
    restart: unless-stopped
    networks:
      - reflectly_network
    env_file:
      - .env
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
networks:
  reflectly_network:
    driver: bridge

