[project]
name = "reflectly"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "uvicorn>=0.40.0",
]
